### ISSUE TITLE
html links broken

### ISSUE THREAD

**Issue by under-score** [laurenwaller/cssco#14]
html links are broken after applying a filter, see https://www.wjst.de/images/pretty/central/2014RedhookCriteriumMilano/20141011_212151__DSC4829.jpg

**Comment by laurenwaller** [comment]
@under-score The cssco class adds an absolutely positioned pseudo element (:after) on top of the contents inside it's container, so when those classes are added to your photo, the filter is added above your anchor, therefore breaking the link.

You could solve this by putting the `<div class="cssco cssco--xx"><img src=""></div>` container INSIDE the anchor, as opposed to outside, so that the pseudo element doesn't affect the anchor?

**Comment by under-score** [comment]
super, that's it

**Comment by laurenwaller** [comment]
@under-score 👍
